### PR TITLE
Coreos deploy

### PR DESCRIPTION
**Pull request by tank157**
Migrates the build and deploy to coreos. Once signed off, we'll alter Buildkite to the new structure.

Assigning to @tie-rack

### CODE REVIEW

**Comment by tie-rack** [comment]
Any reason for moving Buildkite scripts from /script to the root? Buildkite is failing because of that.

**Comment by cap10morgan** [comment]
@tie-rack For very simple repos consisting of a few files, it made more sense to me to just have the scripts in the root. It's very easy to fix in BuildKite.

**Comment by tank157** [comment]
What @cap10morgan said. Since we don't have our own source code here, there didn't seem to be a need to put the scripts off into their own space.

**Comment by tie-rack** [comment]
Okay, but those scripts are about building and deploying, while the rest of the files are about running a papertrail service. It makes _some_ sense to keep them separated.

Do you want to change the Buildkite setup for this project (and make it unlike all our others) so we can see if Buildkite likes these scripts?

**Comment by tank157** [comment]
It's not unlike all our others, the Wildfly build is done in the same way (which is why I asked Wes about it and why I moved these scripts). I'll update BuildKite and make sure it all works from there, and not just from running it locally.

**Comment by cap10morgan** [comment]
@tie-rack Other repos do it this way too. See https://github.com/democracyworks/wildfly-coreos?files=1 for example.

**Comment by tie-rack** [comment]
LGTM! Thank you!

**Pull request merged**
